export enum TipoCampo {
  TEXTO = 'TEXTO',
  NUMERO = 'NUMERO',
  FECHA = 'FECHA',
  SI_NO = 'SI_NO',
  SELECCION_UNICA = 'SELECCION_UNICA',
  SELECCION_MULTIPLE = 'SELECCION_MULTIPLE',
  GPS = 'GPS',
  FOTO = 'FOTO',
  FIRMA = 'FIRMA',
  ARCHIVO = 'ARCHIVO',
}
